name: CI

on:
  push:
    branches:
      - main
  pull_request:

# make sure steps are run in a login shell to support Lmod modules
defaults:
  run:
    shell: bash -l {0}

jobs:
   style:
     runs-on: ubuntu-20.04
     container:
       image: uvilla/class-ci:latest
       options: --user 1001 --privileged
     name: GSL test

     steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Query modules loaded
          run:  module list
        - name: Configure
          run: cd ./lectures/09_AdvancedBuildSystems_DeveloperMode/additional-examples/autotools_with_tests && ml gsl && autoreconf -f -i && ./configure
        - name: Build and test  
          run: cd ./lectures/09_AdvancedBuildSystems_DeveloperMode/additional-examples/autotools_with_tests && ml gsl && make check
        - name: Output
          run: cat ./lectures/09_AdvancedBuildSystems_DeveloperMode/additional-examples/autotools_with_teststest/test-suite.log
